// Generated by tools/bake-mon.py. Do not edit; re-run the script.
#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MON_N 128
#define MON_COUNT 11
#define MON_SDF_SCALE 4   // sdf units per motif pixel; 128 = the edge

extern const char *const mon_names[MON_COUNT];
extern const uint8_t mon_radius[MON_COUNT];   // farthest inside pixel from centre, px
extern const uint8_t mon_sdf[MON_COUNT][MON_N * MON_N];

#ifdef __cplusplus
}
#endif
