#!/usr/bin/env python3
"""Bake the Japanese mon (family crest) silhouettes into 128x128 signed-distance
fields for effects/mon.c.

Source: the RGBA textures Paper Cranes' wall shader already uses (alpha =
silhouette coverage), so the badge, the wall and the 3D-printed bead share one
shape. Output: effects/mon_data.c / mon_data.h, plus a contact sheet PNG for a
quick eyeball check.

    uv run --with pillow --with numpy --with scipy tools/bake-mon.py [src_dir] [sheet.png]

Encoding: value = 128 + 4 * d, where d is the distance to the crest edge in
motif pixels (positive outside, negative inside), clamped to +/-32 px. The
sub-pixel position of the edge comes from the alpha coverage of boundary
cells, so the field is smooth enough to be magnified ~2x on the panel.
"""
import pathlib
import sys

import numpy as np
from PIL import Image
from scipy import ndimage

N = 128
SCALE = 4
# Order matters: index == variant number in the firmware. Append only.
NAMES = ["kiku", "tomoe", "kikyo", "ume", "hakkaku", "mokko", "kikko",
         "suhama", "matsukawa", "katabami", "ogi"]

root = pathlib.Path(__file__).resolve().parents[1]
src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(r"D:\Projects\pc-lab-tile\public\images\beads")
sheet_path = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else None
out_c = root / "effects" / "mon_data.c"
out_h = root / "effects" / "mon_data.h"

fields, radii = [], []
for name in NAMES:
    im = Image.open(src / f"mon-{name}.png").convert("RGBA")
    a = np.asarray(im)[..., 3].astype(np.float32) / 255.0
    if a.shape[0] % N or a.shape[1] % N:
        raise SystemExit(f"{name}: {a.shape} is not a multiple of {N}")
    f = a.shape[0] // N
    cov = a.reshape(N, f, N, f).mean(axis=(1, 3))          # area-average downsample
    mask = cov > 0.5
    d_in = ndimage.distance_transform_edt(mask)              # inside px -> nearest outside px
    d_out = ndimage.distance_transform_edt(~mask)            # outside px -> nearest inside px
    d = np.where(mask, -(d_in - 0.5), d_out - 0.5)
    edge = (cov > 0.0) & (cov < 1.0)                         # boundary cells: sub-pixel from coverage
    d = np.where(edge, 0.5 - cov, d)
    v = np.clip(np.rint(128 + SCALE * d), 0, 255).astype(np.uint8)
    ys, xs = np.nonzero(mask)
    r = float(np.sqrt((ys - (N - 1) / 2) ** 2 + (xs - (N - 1) / 2) ** 2).max()) if len(ys) else 1.0
    fields.append(v)
    radii.append(int(round(r)))
    print(f"{name:10s} inside {mask.mean():5.1%}  radius {r:5.1f} px  sdf {int(v.min())}..{int(v.max())}")

with out_h.open("w", newline="\n") as h:
    h.write("// Generated by tools/bake-mon.py. Do not edit; re-run the script.\n")
    h.write("#pragma once\n#include <stdint.h>\n\n")
    h.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
    h.write(f"#define MON_N {N}\n#define MON_COUNT {len(NAMES)}\n")
    h.write(f"#define MON_SDF_SCALE {SCALE}   // sdf units per motif pixel; 128 = the edge\n\n")
    h.write("extern const char *const mon_names[MON_COUNT];\n")
    h.write("extern const uint8_t mon_radius[MON_COUNT];   // farthest inside pixel from centre, px\n")
    h.write("extern const uint8_t mon_sdf[MON_COUNT][MON_N * MON_N];\n\n")
    h.write("#ifdef __cplusplus\n}\n#endif\n")

with out_c.open("w", newline="\n") as c:
    c.write(f"// Generated by tools/bake-mon.py from {src.as_posix()}. Do not edit.\n")
    c.write("#include \"mon_data.h\"\n\n")
    c.write("const char *const mon_names[MON_COUNT] = {" + ", ".join(f'"{n}"' for n in NAMES) + "};\n")
    c.write("const uint8_t mon_radius[MON_COUNT] = {" + ", ".join(str(r) for r in radii) + "};\n\n")
    c.write("const uint8_t mon_sdf[MON_COUNT][MON_N * MON_N] = {\n")
    for name, v in zip(NAMES, fields):
        c.write(f"  // {name}\n  {{\n")
        flat = v.reshape(-1)
        for i in range(0, flat.size, 32):
            c.write("    " + ",".join(str(int(x)) for x in flat[i:i + 32]) + ",\n")
        c.write("  },\n")
    c.write("};\n")
print(f"wrote {out_c} ({out_c.stat().st_size // 1024} KB) and {out_h}")

if sheet_path:
    cols = 4
    rows = (len(NAMES) + cols - 1) // cols
    sheet = Image.new("L", (cols * N, rows * N), 0)
    for i, v in enumerate(fields):
        # show the silhouette (edge at 128) with a faint distance ramp outside
        img = np.where(v < 128, 255, np.clip(200 - (v.astype(int) - 128) * 6, 0, 120)).astype(np.uint8)
        sheet.paste(Image.fromarray(img), ((i % cols) * N, (i // cols) * N))
    sheet.save(sheet_path)
    print(f"wrote {sheet_path}")
